### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by yermulnik** [noborus/homebrew-tap#1]
Just got a warning from `brew outdated`:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the noborus/tap tap (not Homebrew/brew or Homebrew/core):
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/noborus/homebrew-tap/trdsql.rb:5
```

**Comment by der-bingle** [comment]
Just got the same warning as @yermulnik, except now it's an error that prevents the tools from being installed at all. 😕

**Comment by yermulnik** [comment]
The latest `trdsql` brew formulae (https://github.com/noborus/homebrew-tap/blob/master/trdsql.rb) has no `bottle :unneeded` spec, so you should be good to run `brew update && brew upgrade trdsql`.

**Comment by noborus** [comment]
This has been fixed, so I will close it.
Thank you.
