### ISSUE TITLE
invalid formulae (breaking `brew info`) missing URL: mdtsql & psutilsql.rb

### ISSUE THREAD

**Issue by stefanwascoding** [noborus/homebrew-tap#3]
Hi

I've tapped this repo to use your tools, but unfortunately at least on a M1 MBP running the latest Ventura, this breaks the command `brew info --json=v2 --eval-all`:

![brew info fail](https://github.com/noborus/homebrew-tap/assets/2292035/9faadc9d-b81f-403f-aa33-d3d04e5ab2f3)

If you check what is causing the formula without URL error using `brew readall --eval-all` you get:

![readall](https://github.com/noborus/homebrew-tap/assets/2292035/99436bd1-d93c-4036-982c-b6958950da3f)

When we delete those two files (`rm /opt/homebrew/Library/Taps/noborus/homebrew-tap/{mdtsql,psutilsql}.rb`), the `brew info --json=v2 --eval-all` command now succeeds.

Would it be possible to modify those two formulae (mdtsql & psutilsql) to be valid on macOS as well?

**Comment by noborus** [comment]
Thank you for the issue. 
I am sorry for my late response.
I created a macOS version of mdtsql & psutilsql.

**Comment by stefanwascoding** [comment]
Just tested, and works for me.  👍🏻  Thanks.
